docker-up:
	docker-compose -f ./docker/docker-compose.yml up -d
docker-stop:
	docker-compose -f ./docker/docker-compose.yml stop
docker-down:
	docker-compose -f ./docker/docker-compose.yml down

docker-refresh: docker-down docker-up